In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
from math import ceil, sqrt

In [38]:
n_images = 5
sidelen = n_images
step_size = 1 / sidelen
grid_points_x = np.arange(0, 1 - step_size/2, step_size)
grid_points_y = np.arange(0, 1 - step_size/2, step_size)
start_xs, start_ys = np.meshgrid(grid_points_x, grid_points_y, indexing='ij')
n_rows = 5
step_sizes = np.full(n_rows, step_size)
margin = 0.05 * step_size / 2



In [39]:
start_xs.ravel()[:n_rows], start_xs.ravel()

(array([0., 0., 0., 0., 0.]),
 array([0. , 0. , 0. , 0. , 0. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.4, 0.4,
        0.4, 0.4, 0.6, 0.6, 0.6, 0.6, 0.6, 0.8, 0.8, 0.8, 0.8, 0.8]))

In [40]:
sidelen, step_size

(5, 0.2)

In [41]:
grid_points

array([0.        , 0.33333333, 0.66666667])

In [42]:
start_xs

array([[0. , 0. , 0. , 0. , 0. ],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.4, 0.4, 0.4, 0.4, 0.4],
       [0.6, 0.6, 0.6, 0.6, 0.6],
       [0.8, 0.8, 0.8, 0.8, 0.8]])

In [43]:
start_ys

array([[0. , 0.2, 0.4, 0.6, 0.8],
       [0. , 0.2, 0.4, 0.6, 0.8],
       [0. , 0.2, 0.4, 0.6, 0.8],
       [0. , 0.2, 0.4, 0.6, 0.8],
       [0. , 0.2, 0.4, 0.6, 0.8]])

In [45]:
grid_points_x

array([0. , 0.2, 0.4, 0.6, 0.8])